# Generated by Django 5.2.1 on 2025-05-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userregisterview_alter_customuser_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRegisterView",
        ),
    ]
