# Generated by Django 5.2.1 on 2025-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_delete_userregisterview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                to="auth.group",
                verbose_name="Группы",
            ),
        ),
    ]
