# Generated by Django 5.2.1 on 2025-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options_mailing_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Рассылка завершена: "
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Рассылка отправлена: "
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(max_length=20, verbose_name="Статус рассылки: "),
        ),
    ]
