# Generated by Django 5.2.1 on 2025-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_owner_alter_message_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
