# Generated by Django 5.2.1 on 2025-06-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_mailingattempt_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_switch_off_mailing", "Может отключить рассылку"),
                    ("can_view_all_mailings", "Может смотреть все рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
