# Generated by Django 5.2.1 on 2025-06-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_message", "Может смотреть сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["fullname"],
                "permissions": [("can_view_recipient", "Может смотреть получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
