# Generated by Django 5.2.1 on 2025-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_alter_message_options_alter_recipient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient_email",
            field=models.CharField(default=""),
        ),
    ]
